data_source duckdb_datasource:
  type: duckdb
  connection:
    database: memory
    extensions:
      - delta


{# data_source duckdb_datasource:
  type: duckdb
  connection:
    database: /tmp/soda_scan.duckdb
    extensions:
      - delta #}
